name: BughuntCICDCanaryTest

on:
  push:
    branches: [ 'BughuntCICDCanaryDestination-**' ]
  pull_request:
    branches: [ 'BughuntCICDCanaryDestination-**' ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Configure AWS Credentials CodeGuru
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ always() }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_IAD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAD }}
          aws-region: us-east-1

      - name: Checkout the CodeGuru Reviewer Action repository
        uses: actions/checkout@v2
        if: ${{ always() }}
        with:
          repository: vijejain/cicd-actions-bugbash
          ref: refs/heads/prod-endpoint
          token: ${{ secrets.TOKEN }}
          path: ./.github/vijejain/cicd-actions-bugbash

      - name: AWS CodeGuru Reviewer Scanner
        uses: ./.github/vijejain/cicd-actions-bugbash
        if: ${{ always() }}
        with:
          name: BughuntCICDCanary-prod
          source_path: .
          build_path: buildFiles
          s3_bucket: codeguru-reviewer-cicd-github-canary-prod-us-east-1

      - name: Upload review result
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeguru-results.sarif.json

      # Add this step to assist debugging
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: sarif_results
          path: codeguru-results*.json